# Generated by Django 3.1.3 on 2020-11-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20201114_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='selections',
            field=models.ManyToManyField(to='vote.Option'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
    ]
