# Generated by Django 3.1.3 on 2020-11-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_election_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
